### ISSUE TITLE
redefine argon2 parameters for both trivial and time-intensive hashings

### ISSUE THREAD

**Issue by Yuri-SVB** [Yuri-SVB/Great_Wall#3]
This is critical because the more different version of hashes parameters, the more prone to compatibility bugs, as in _versioning bug causes user to derive different keys_. From the point of UX, this leads to time loss at best, until user figures out correct version, all the way through anxiety or catastrophic deadlock at worse, is correct version is lost.

Object-orienting the hashing portion of the GreatWall class ([another issue](https://github.com/Yuri-SVB/Great_Wall/issues/2)) would contribute to organization and to minimize that risk.

**Comment by MuhammadMuradG** [comment]
Closing this as addressed by #18 PR.
