### ISSUE TITLE
Change feedback formula for parameters.

### ISSUE THREAD

**Issue by Yuri-SVB** [Yuri-SVB/Great_Wall#31]
Take 2 bytes, convert them into integer (between 0 and 2^16-1 = 65535)
then you invert the decimal digits. Example: suppose the resulting integer is 12345. In this case the parameter p equals 2.54321 .
Same for imaginary, just with other 2 integers.

Those integers should come from a digest of a hash having as input the current state, and salted by the indexation of the choice at hand, and a label indicating real or imaginary.

**Comment by MuhammadMuradG** [comment]
Closing this as it has been addressed in #40 PR.
