### ISSUE TITLE
Images pixelated

### ISSUE THREAD

**Issue by Yuri-SVB** [Yuri-SVB/Great_Wall#33]
Image seems pixelated even at zoom out. Apparent size of pixels is seemingly unaltered for a certain range of zoom. Proposed improvements:
- Increase the size of subwindows;
- Change rendering of subwindow from color map;
- Change color scheme; (see issue #32.)

**Comment by MuhammadMuradG** [comment]
Close this as it has been addressed in #51 and #36 PRs.
