### ISSUE TITLE
Implement fractal-image minimization and rearrangement

### ISSUE THREAD

**Issue by rainman456** [Yuri-SVB/Great_Wall#43]
This issue is to facilitate the comparison or selection whenever too many options are presented, due to need for scrolling to see those options.
- addition of a minimization button 
-  addition  of  collapsing sub-windows for fractal images
- addition of a button that collapses and automatically puts the collapsed image in the bottom

**Comment by fredericomba** [comment]
There should also be a "drag-and-drop" feature for the image.

**Comment by MuhammadMuradG** [comment]
Close this as it has been solved in #52 PR.
