### ISSUE TITLE
Failure to get final result when using "Formosa" tacit knowledge type

### ISSUE THREAD

**Issue by fredericomba** [Yuri-SVB/Great_Wall#49]
I have decided to use the "Formosa" tacit knowledge type when testing the program because it's the one that runs the fastest in the computer I use (there are no images to be rendered, unlike Mandelbrot). However, when reaching the final screen, I should be able to get the result (the secret seed that actually unlocks the Bitcoin) like I have managed to do using Mandelbrot, but it doesn't move forward. Unlike on the previous steps, pressing the buttons to select which leaf from the tree to move next makes no change.

![quickshot_240229_074631](https://github.com/Yuri-SVB/Great_Wall/assets/11416855/93d9b095-5c2d-4816-ae34-618d5f131936)
Screenshot: after clicking either "dancer hide classical oar artisan court" or "wizard trust nickel claw valkyrie paradise", the result view should be presented, but nothing happens instead.

**Comment by MuhammadMuradG** [comment]
Closing this as it has been addressed in #60.
