### ISSUE TITLE
Abstract different TKBA approaches

### ISSUE THREAD

**Issue by Yuri-SVB** [Yuri-SVB/Great_Wall#54]
Create an abstract class representing an undefined amount (possibly a tuple) of parameters, for an undefined TKBA approach. This abstract class should be overriden for each given TKBA approach (fractal, Formosa, sound effect, etc.). In each such override class, virtual methods for deriving parameters from (candidate of next) L_i should be particularly instantiated.

**Comment by MuhammadMuradG** [comment]
Closing this as completed in #82.
