### ISSUE TITLE
the logs show that the method of deriving state is being entered in a duplicated form.

### ISSUE THREAD

**Issue by flatFeather** [Yuri-SVB/Great_Wall#55]
Applicationn flow is entering twice in selection_derive_state_n_entered method, 
![image](https://github.com/Yuri-SVB/Great_Wall/assets/158213130/c88c7588-c3b4-491c-abb1-219c566be066)

The duplicated level_up_signal is probably being emitted.

**Comment by turizspace** [comment]
assign me this.

**Comment by MuhammadMuradG** [comment]
Closing this as it has been addressed in #60 PR.
